---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
   - staging_vpc_info
  vars:
   region: us-west-2
   key: ansible-4-aws-test
   instance_type: t2.nano
   image: ami-1e299d7e
   prefix: staging
  tasks:
   - name: database instance provisioning
     ec2:
      region: "{{ region }}"
      key_name: "{{ key }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      group: "{{ prefix }}_sg_database"
      instance_tags:
       Name: "{{ prefix }}_database"
       class: database
       environment: staging
      id: db_launch_01
      vpc_subnet_id: "{{ staging_subnet_private }}"
      assign_public_ip: no
