---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
   - staging_vpc_info
  vars:
   region: us-west-2
   key: ansible-4-aws-test
   instance_type: t2.nano
   image: ami-1e299d7e
   prefix: staging
   vpc_subnet_id: "{{ staging_subnet_public }}"
  tasks:
   - name: jump box instance provisioning
     ec2:
      region: "{{ region }}"
      key_name: "{{ key }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      group: "{{ prefix }}_sg_jumpbox"
      instance_tags:
       Name: "{{ prefix }}_jumpbox"
       class: jumpbox
       environment: "{{ prefix }}"
      id: jumbox_launch_01
      vpc_subnet_id: "{{ vpc_subnet_id }}"
     register: ec2
   - name: associate new EIP for the instance
     ec2_eip:
      region: "{{ region }}"
      instance_id: "{{ item }}"
     with_items: "{{ ec2.instance_ids }}"
