---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
   region: us-west-2
   instance_type: t2.micro
   image: ami-1e299d7e
   key: ansible-4-aws-test
  tasks:
   - name: Launch ec2 with tags webserver staging
     ec2:
      region: "{{ region }}"
      key_name: "{{ key }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      group: sg_webserver_ansible4aws
      instance_tags:
       Name: staging-webserver-1
       class: webserver
       environment: staging
   - name: Launch ec2 with tags webserver production
     ec2:
      region: "{{ region }}"
      key_name: "{{ key }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      group: sg_webserver_ansible4aws
      instance_tags:
       Name: production-webserver-1
       class: webserver
       environment: production
   - name: Launch ec2 with tags database staging
     ec2:
      region: "{{ region }}"
      key_name: "{{ key }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      group: sg_database_ansible4aws
      instance_tags:
       Name: staging-database-1
       class: database
       environment: staging
