---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
   region: us-west-2
  vars_files:
   - staging_vpc_info
  tasks:
   - name: delete vpc
     ec2_vpc:
      region: "{{ region }}"
      state: absent
      vpc_id: "{{ staging_vpc }}"
      resource_tags: '{"Name":"staging_vpc"}'
      wait: yes
