---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
   region: us-west-2
   prefix: staging
   # availability zones
   az0: us-west-2b
   az1: us-west-2c
  tasks:
   - name: create vpc with multi-az subnets
     ec2_vpc:
      region: "{{ region }}"
      cidr_block: 10.0.0.0/16
      resource_tags: '{"Name":"{{ prefix }}_vpc"}'
      subnets:
       - cidr: 10.0.0.0/24
         az: "{{ az0 }}"
         resource_tags: '{"Name":"{{ prefix }}_subnet_public_0"}'
       - cidr: 10.0.1.0/24
         az: "{{ az0 }}"
         resource_tags: '{"Name":"{{ prefix }}_subnet_private_0"}'
       - cidr: 10.0.2.0/24
         az: "{{ az1 }}"
         resource_tags: '{"Name":"{{ prefix }}_subnet_public_1"}'
       - cidr: 10.0.3.0/24
         az: "{{ az1 }}"
         resource_tags: '{"Name":"{{ prefix }}_subnet_private_1"}'
      internet_gateway: yes
      route_tables:
       - subnets:
          - 10.0.0.0/24
          - 10.0.2.0/24
         routes:
          - dest: 0.0.0.0/0
            gw: igw
     register: vpc
   - name: write vpc id to {{ prefix }}_vpc_multiaz_info file
     shell: echo "{{ prefix }}"_vpc":" "{{ vpc.vpc_id }}" > "{{ prefix }}"_vpc_multiaz_info
   - name: write subnets ids to {{ prefix }}_vpc_multiaz_infofile
     shell: echo "{{ item.resource_tags.Name }}"":" "{{ item.id }}" >> "{{ prefix }}"_vpc_multiaz_info
     with_items: "{{ vpc.subnets }}"
