---
- hosts: localhost
  connection: local 
  gather_facts: no
  vars:
   region: us-west-2
   keyname: ansible-4-aws-test
   instance_type: t2.micro
   env: staging
   image: ami-1e299d7e
   ins_name: wordpress_master
  tasks:
    - name: get {{ env }}_vpc id
      command: "aws ec2 describe-vpcs 
                --region {{ region }}
                --filters Name=tag:Name,Values={{ env }}_vpc
                --query 'Vpcs[0].VpcId' --output text"
      register: vpc_id 

    - name: "get {{ env }}_subnet_public_0 subnet id"
      command: "aws ec2 describe-subnets 
                --region {{ region }} 
                --filters Name=tag:Name,Values={{ env }}_subnet_public_0
                --query 'Subnets[0].SubnetId' --output text"
      register: subnet0

    - name: launch ec2 instance 
      ec2:
       region: "{{ region }}"
       key_name: "{{ keyname }}"
       instance_type: "{{ instance_type }}"
       image: "{{ image }}"
       wait: yes
       group: "{{ env }}_sg_web"
       instance_tags:
        Name: "{{ ins_name }}"
        class: wordpress_ha 
       vpc_subnet_id: "{{ subnet0.stdout }}"
      register: ec2
      when: subnet0.stdout!="None"

    - name: check EIP association
      command: "aws ec2 describe-instances
                --region {{ region }}
                --filters Name=tag:Name,Values={{ ins_name }}
                --query 'Reservations[0].Instances[0].NetworkInterfaces[0].Association'
                --output text"
      register: eip 

    - debug: var=ec2
    - debug: var=eip

    - name: associate new EIP for the instance
      ec2_eip:
       region: "{{ region }}"
       instance_id: "{{ item.id }}"
      with_items: "{{ ec2.instances }}"
      when: item.id is defined and eip.stdout=="None"

